2012/08/24 00:40:07 [error] [exception.CException] exception 'CException' with message 'SiteController and its behaviors do not have a method or closure named "getRequest".' in C:\xampp\htdocs\libs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\projetos\sites\youtroll\protected\controllers\site\IndexAction.php(8): CComponent->__call('getRequest', Array)
#1 C:\xampp\htdocs\projetos\sites\youtroll\protected\controllers\site\IndexAction.php(8): SiteController->getRequest('POST', 'LoginForm')
#2 C:\xampp\htdocs\libs\yii\framework\web\actions\CAction.php(75): IndexAction->run()
#3 C:\xampp\htdocs\libs\yii\framework\web\CController.php(309): CAction->runWithParams(Array)
#4 C:\xampp\htdocs\libs\yii\framework\web\CController.php(287): CController->runAction(Object(IndexAction))
#5 C:\xampp\htdocs\libs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(IndexAction), Array)
#6 C:\xampp\htdocs\libs\yii\framework\web\CWebApplication.php(276): CController->run('')
#7 C:\xampp\htdocs\libs\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('')
#8 C:\xampp\htdocs\libs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\projetos\sites\youtroll\index.php(10): CApplication->run()
#10 {main}
REQUEST_URI=/projetos/sites/youtroll/
---
2012/08/24 00:41:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "sites/index".' in C:\xampp\htdocs\libs\yii\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\libs\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('sites/index')
#1 C:\xampp\htdocs\libs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\projetos\sites\youtroll\index.php(10): CApplication->run()
#3 {main}
REQUEST_URI=/projetos/sites/youtroll/sites/index
---
2012/09/01 00:17:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "]".' in C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php:280
Stack trace:
#0 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(135): CWebApplication->runController(']')
#1 C:\xampp\htdocs\youtroll\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\youtroll\index.php(10): CApplication->run()
#3 {main}
REQUEST_URI=/youtroll/]
---
2012/09/08 19:50:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'O sistema não foi capaz de encontrar a ação "index" solicitada.' in C:\xampp\htdocs\youtroll\yii\framework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(271): CController->missingAction('')
#1 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(276): CController->run('')
#2 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('user')
#3 C:\xampp\htdocs\youtroll\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\youtroll\api\index.php(10): CApplication->run()
#5 {main}
REQUEST_URI=/youtroll/api/user
---
2012/09/08 19:52:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'O sistema não foi capaz de encontrar a ação "index" solicitada.' in C:\xampp\htdocs\youtroll\yii\framework\web\CController.php:484
Stack trace:
#0 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(271): CController->missingAction('')
#1 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(276): CController->run('')
#2 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('user')
#3 C:\xampp\htdocs\youtroll\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#4 C:\xampp\htdocs\youtroll\api\index.php(10): CApplication->run()
#5 {main}
REQUEST_URI=/youtroll/api/user
---
2012/09/08 19:53:36 [error] [php] include(User.php): failed to open stream: No such file or directory (C:\xampp\htdocs\youtroll\yii\framework\YiiBase.php:418)
Stack trace:
#0 C:\xampp\htdocs\youtroll\api\protected\controllers\UserController.php(8): spl_autoload_call()
#1 C:\xampp\htdocs\youtroll\yii\framework\web\actions\CInlineAction.php(50): UserController->actionList()
#2 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(287): UserController->runAction()
#4 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(266): UserController->runActionWithFilters()
#5 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(276): UserController->run()
#6 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(135): CWebApplication->runController()
#7 C:\xampp\htdocs\youtroll\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#8 C:\xampp\htdocs\youtroll\api\index.php(10): CWebApplication->run()
REQUEST_URI=/youtroll/api/user
in C:\xampp\htdocs\youtroll\api\protected\controllers\UserController.php (8)
in C:\xampp\htdocs\youtroll\api\index.php (10)
2012/09/08 19:55:16 [error] [exception.CHttpException.500] exception 'CHttpException' with message 'Erro Interno do Servidor' in C:\xampp\htdocs\youtroll\api\protected\models\helpers\ApplicationHelper.php:32
Stack trace:
#0 C:\xampp\htdocs\youtroll\api\protected\models\helpers\ApplicationHelper.php(51): ApplicationHelper::throwException(500)
#1 C:\xampp\htdocs\youtroll\api\protected\controllers\UserController.php(14): ApplicationHelper::ajaxResponse(Array)
#2 C:\xampp\htdocs\youtroll\yii\framework\web\actions\CInlineAction.php(50): UserController->actionList()
#3 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(276): CController->run('list')
#7 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('user/list')
#8 C:\xampp\htdocs\youtroll\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\youtroll\api\index.php(10): CApplication->run()
#10 {main}
REQUEST_URI=/youtroll/api/user
---
2012/09/08 19:57:18 [error] [exception.CHttpException.500] exception 'CHttpException' with message 'Erro Interno do Servidor' in C:\xampp\htdocs\youtroll\api\protected\models\helpers\ApplicationHelper.php:32
Stack trace:
#0 C:\xampp\htdocs\youtroll\api\protected\models\helpers\ApplicationHelper.php(51): ApplicationHelper::throwException(500)
#1 C:\xampp\htdocs\youtroll\api\protected\controllers\UserController.php(14): ApplicationHelper::ajaxResponse(Array)
#2 C:\xampp\htdocs\youtroll\yii\framework\web\actions\CInlineAction.php(50): UserController->actionList()
#3 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(276): CController->run('list')
#7 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('user/list')
#8 C:\xampp\htdocs\youtroll\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\youtroll\api\index.php(10): CApplication->run()
#10 {main}
REQUEST_URI=/youtroll/api/user
---
2012/09/08 19:57:34 [error] [exception.CHttpException.500] exception 'CHttpException' with message 'Erro Interno do Servidor' in C:\xampp\htdocs\youtroll\api\protected\models\helpers\ApplicationHelper.php:32
Stack trace:
#0 C:\xampp\htdocs\youtroll\api\protected\models\helpers\ApplicationHelper.php(51): ApplicationHelper::throwException(500)
#1 C:\xampp\htdocs\youtroll\api\protected\controllers\UserController.php(14): ApplicationHelper::ajaxResponse(Array)
#2 C:\xampp\htdocs\youtroll\yii\framework\web\actions\CInlineAction.php(50): UserController->actionList()
#3 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(276): CController->run('list')
#7 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('user/list')
#8 C:\xampp\htdocs\youtroll\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\youtroll\api\index.php(10): CApplication->run()
#10 {main}
REQUEST_URI=/youtroll/api/user
---
2012/09/08 19:57:45 [error] [exception.CHttpException.500] exception 'CHttpException' with message 'Erro Interno do Servidor' in C:\xampp\htdocs\youtroll\api\protected\models\helpers\ApplicationHelper.php:32
Stack trace:
#0 C:\xampp\htdocs\youtroll\api\protected\models\helpers\ApplicationHelper.php(51): ApplicationHelper::throwException(500)
#1 C:\xampp\htdocs\youtroll\api\protected\controllers\UserController.php(14): ApplicationHelper::ajaxResponse(Array)
#2 C:\xampp\htdocs\youtroll\yii\framework\web\actions\CInlineAction.php(50): UserController->actionList()
#3 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\youtroll\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(276): CController->run('list')
#7 C:\xampp\htdocs\youtroll\yii\framework\web\CWebApplication.php(135): CWebApplication->runController('user/list')
#8 C:\xampp\htdocs\youtroll\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#9 C:\xampp\htdocs\youtroll\api\index.php(10): CApplication->run()
#10 {main}
REQUEST_URI=/youtroll/api/user
---
